IZIVIA/ocpi-toolkit

ocpi-toolkit-2.1.1-gireve/src/main/kotlin/com/izivia/ocpi/toolkit/common/HttpUtils.kt
ocpi-toolkit-2.1.1-gireve/src/main/kotlin/com/izivia/ocpi/toolkit/modules/credentials/repositories/PlatformRepository.kt
ocpi-toolkit-2.1.1-gireve/src/main/kotlin/com/izivia/ocpi/toolkit/modules/credentials/services/CredentialsServerService.kt
ocpi-toolkit-2.1.1-gireve/src/test/kotlin/com/izivia/ocpi/toolkit/samples/common/DummyPlatformCacheRepository.kt
ocpi-toolkit-2.1.1-gireve/src/test/kotlin/com/izivia/ocpi/toolkit/samples/common/Platform.kt
ocpi-toolkit-2.1.1-gireve/src/test/kotlin/com/izivia/ocpi/toolkit/samples/common/PlatformCacheRepository.kt
ocpi-toolkit-2.1.1-gireve/src/test/kotlin/com/izivia/ocpi/toolkit/samples/credentials/CredentialsReceiver.kt
ocpi-toolkit-2.1.1-gireve/src/test/kotlin/com/izivia/ocpi/toolkit/samples/credentials/CredentialsSender.kt
ocpi-toolkit-2.1.1-gireve/src/test/kotlin/com/izivia/ocpi/toolkit/tests/integration/mock/PlatformMongoRepository.kt
ocpi-toolkit-2.1.1/src/main/kotlin/com/izivia/ocpi/toolkit/common/HttpUtils.kt
ocpi-toolkit-2.1.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/credentials/repositories/PlatformRepository.kt
ocpi-toolkit-2.1.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/credentials/services/CredentialsServerService.kt
ocpi-toolkit-2.1.1/src/test/kotlin/com/izivia/ocpi/toolkit/samples/common/DummyPlatformCacheRepository.kt
ocpi-toolkit-2.1.1/src/test/kotlin/com/izivia/ocpi/toolkit/samples/common/Platform.kt
ocpi-toolkit-2.1.1/src/test/kotlin/com/izivia/ocpi/toolkit/samples/common/PlatformCacheRepository.kt
ocpi-toolkit-2.1.1/src/test/kotlin/com/izivia/ocpi/toolkit/samples/credentials/CredentialsReceiver.kt
ocpi-toolkit-2.1.1/src/test/kotlin/com/izivia/ocpi/toolkit/samples/credentials/CredentialsSender.kt
ocpi-toolkit-2.1.1/src/test/kotlin/com/izivia/ocpi/toolkit/tests/integration/mock/PlatformMongoRepository.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/common/HttpUtils.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/credentials/repositories/PlatformRepository.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/credentials/services/CredentialsServerService.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/samples/common/DummyPlatformCacheRepository.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/samples/common/Platform.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/samples/common/PlatformCacheRepository.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/samples/credentials/CredentialsReceiver.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/samples/credentials/CredentialsSender.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/tests/integration/mock/PlatformMongoRepository.kt

All OCPI versions are impacted. This is a breaking change that increases compatibility with partners as receiver.
**Purpose**
These changes prevent you, as a receiver, to ask for your partner URL before a handshake. Before these changes, you had to ask for your partner to give you their versions URL so that you can initialize a `Platform` object with both the `url` and the `tokenA`.
Now, as the OCPI protocol states, you just need (as a receiver), to give a `tokenA` to your partner.
**Why these technical changes**
It is now possible that a `Platform` object only contains a token A before handshake. So the code had to be updated accordingly. Before, it was coded following the assumption that a platform must have at least an `url`. On your side, only the `PlatformRepository` has been updated …

fix(ocpi-2.2.1,2.1.1,2.1.1-gireve): receiver should not know sender url before handshake

---

.editorconfig
README.md
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/common/HttpUtils.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/common/OcpiResponseBody.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/credentials/CredentialsClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/credentials/services/CredentialsServerService.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/locations/LocationsCpoClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/locations/LocationsEmspClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/sessions/SessionsCpoClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/sessions/SessionsEmspClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/tokens/TokensCpoClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/tokens/TokensEmspClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/versions/VersionDetailsClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/versions/VersionsClient.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/samples/common/Http4kTransportClient.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/samples/common/Http4kTransportServer.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/tests/integration/CredentialsIntegrationTests.kt
transport/src/main/kotlin/com/izivia/ocpi/toolkit/transport/TransportClient.kt

**Only for ocpi 2.2.1**
- `Content-Type: application/json` header is now added on requests if the body is not null
- `Content-Type: application/json` header is now added on all responses
- Headers are not case sensitive anymore. It means that `X-Request-ID` and `X-Correlation-ID` are properly propagated in responses even if the case does not match. Note: `Authorization` header was working because it also accepted `authorization`
- It is now possible to define how `X-Request-ID` and `X-Correlation-ID` are generated. You have to override methods in your `TransportClient` implementation. By default, the behaviour stays the same, it generates a random `UUID`.
**Migration guide**
If you manually added Content-Type header & normalized headers in your Transport implementation, you can remove it. …

fix(ocpi-2.2.1): Add Content-Type header on requests (if needed), on all responses & fixed headers case sensitivity

---

ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/locations/LocationsCpoClient.kt

Fix for issue #24
Did not bother checking v 2.1.1 as @lilgallon mentioned support for it will be dropped anyways.
Did not find any existing tests, so this is fix only.

fix(ocpi-2.2.1): path for PATCH evse and connector

---

ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/sessions/services/SessionsValidators.kt

Removes all comparisons to Instant.Now() for dates
Fixes evseUid check to be uniqueID check instead of emi3ID validation

fix(sessions) #38: Time and EvseUid validation invalid

---

ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/sessions/domain/Session.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/sessions/services/SessionsValidators.kt

Using same datatype as for Cdr.totalEnergy

fix(sessions) #42: Session.kwh should be BigDecimal

---

ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/credentials/services/CredentialsServerService.kt

fix(credentials) throw OcpiServerUnsupportedVersionException when versions doesn't match

---

.github/workflows/publish.yml

- Tested there: https://github.com/lilgallon/ocpi-toolkit/actions/runs/7221032695/job/19675142201
- Produces the same releases as the one we already have, but with built artefacts, as you can see there https://github.com/lilgallon/ocpi-toolkit/releases/tag/R-0.0.27
I am open to critism

feat(ci/cd) #44: Automatic Github release creation on publish

---

ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/common/validation/Validation.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/common/validation/Validators.kt

feat(validation) #71: improve constraint violation readability

---

ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/credentials/services/CredentialsClientService.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/credentials/services/CredentialsServerService.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/locations/services/LocationsCpoService.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/locations/services/LocationsEmspService.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/sessions/services/SessionsCpoService.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/sessions/services/SessionsEmspService.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/tokens/services/TokensCpoService.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/tokens/services/TokensEmspService.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/versions/services/VersionsService.kt

feat(ocpi-2.2.1) open service classes

---

ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/common/OcpiResponseBody.kt

fix: return HTTP 200 on errors from the OCPI layer

---

ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/common/HttpAuthInterface.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/commands/CommandCpoClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/commands/CommandCpoInterface.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/commands/CommandCpoServer.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/commands/CommandEmspClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/commands/CommandEmspInterface.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/commands/CommandEmspServer.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/commands/domain/CancelReservation.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/commands/domain/CommandResponse.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/commands/domain/CommandResponseType.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/commands/domain/CommandResult.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/commands/domain/CommandResultType.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/commands/domain/ReserveNow.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/commands/domain/StartSession.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/commands/domain/StopSession.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/commands/domain/UnlockConnector.kt

Implementor is responsible for async handling of calling callback via the client
Example implementation of postStartSession
```
override suspend fun postStartSession(
partnerUrl: String,
startSession: StartSession,
): OcpiResponseBody<CommandResponse> {
validate {
validateLength("response_url", startSession.responseUrl, 255)
validateLength("token.country_code", startSession.token.countryCode, 2)
validateLength("token.partyId", startSession.token.partyId, 3)
validateLength("token.uid", startSession.token.uid, 36)
validateLength("token.issuer", startSession.token.issuer, 64)
validateLength("location_id", startSession.locationId, 36)
}
val responseType = if (startSession.evseUid == null) {
// we don't allow remote start on a location. This is an implementation detail on our side …
```

feat(commands) #26: Implement Commands module

---

ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/common/HttpUtils.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/common/OcpiToolkitExceptions.kt

fix(transport) #87: Throw explicit exception when a required header is missing

---

ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/common/HttpUtils.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/common/OcpiResponseBody.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/credentials/services/CredentialsClientService.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/credentials/services/CredentialsServerService.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/modules/locations/services/LocationsCpoServiceTest.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/modules/locations/services/LocationsEmspServiceTest.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/modules/tokens/services/TokensCpoServiceTest.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/modules/tokens/services/TokensEmspServiceTest.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/tests/integration/CredentialsIntegrationTests.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/tests/integration/LocationsIntegrationTest.kt

refactor(common) #93: rename to camelCase the fields of OcpiResponseBody

---

ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/common/HttpUtils.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/common/OcpiExceptions.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/common/OcpiResponseBody.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/credentials/services/CredentialsServerService.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/versions/domain/ModuleID.kt

Closes #11 
I think this is a good solution because the result of DELETE requests will usually be empty.
By mistake, but I've pushed a related change that closes #104

fix(common): Successful DELETE requests should return HTTP 200

---

ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/locations/domain/Connector.kt

feat(locations) #130: Skip null values in Connector.tariffIds

---

ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/common/HttpUtils.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/common/OcpiClientUtils.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/cdr/CdrsCpoClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/cdr/CdrsEmspClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/chargingProfiles/ChargingProfilesCpoClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/chargingProfiles/ChargingProfilesScspClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/commands/CommandCpoClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/commands/CommandEmspClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/credentials/repositories/PartnerRepository.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/credentials/services/CredentialsClientService.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/credentials/services/CredentialsServerService.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/locations/LocationsCpoClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/locations/LocationsEmspClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/sessions/SessionsCpoClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/sessions/SessionsEmspClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/tokens/TokensCpoClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/tokens/TokensEmspClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/versions/VersionDetailsClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/versions/VersionsClient.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/samples/common/DummyPartnerCacheRepository.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/samples/common/PartnerCacheRepository.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/samples/credentials/CredentialsSender.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/samples/locations/LocationsCpoClient.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/samples/locations/LocationsEmspClient.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/tests/integration/CredentialsIntegrationTests.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/tests/integration/LocationsIntegrationTest.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/tests/integration/mock/PartnerMongoRepository.kt

Rename parameter `partnerUrl` in search method to allow the usage of another field as a unique identifier for partners
Fix issue: https://github.com/IZIVIA/ocpi-toolkit/issues/132
:warning: This changes may be breaking change for user

feat: rename partnerUrl parameter to partnerId in search method to allow the usage of another field as identifier

---

ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/common/validation/Validators.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/cdr/domain/SignedValue.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/cdr/services/CdrsValidators.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/locations/services/LocationValidators.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/tokens/services/TokenValidators.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/modules/locations/services/LocationsValidatorTest.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/samples/common/ValidDomainObjects.kt

Created exclusion mapping based on information here: https://en.wikipedia.org/wiki/Unicode_control_characters
Ensured there are no ASCII checks where there should be a UTF8 check
Did not check if there are any UTF8 fields with missing checks. Main goal was to avoid failing on valid UTF8

fix(validation) #119: allow valid UTF8 values

---

ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/credentials/services/CredentialsServerService.kt

Move the tokenA invalidation after getCredential in CredentialsServerService, because it is the one that is in the context and used during getCredential
Closes https://github.com/IZIVIA/ocpi-toolkit/issues/138

fix(credentials): move the tokenA invalidation after getCredential

---

ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/credentials/repositories/CredentialsRoleRepository.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/credentials/services/CredentialsClientService.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/credentials/services/CredentialsServerService.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/samples/credentials/CredentialsReceiver.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/samples/credentials/CredentialsSender.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/tests/integration/CredentialsIntegrationTests.kt

Review the https://github.com/IZIVIA/ocpi-toolkit/issues/138 fix

fix(credentials): add partnerId on getCredentialsRoles

---

ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/common/OcpiInstantDeserializer.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/common/OcpiInstantSerializer.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/mappers/MappersTest.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/modules/locations/http/cpo/LocationsCpoHttpGetConnectorTest.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/modules/locations/http/cpo/LocationsCpoHttpGetEvseTest.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/modules/locations/http/cpo/LocationsCpoHttpGetLocationTest.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/modules/locations/http/cpo/LocationsCpoHttpGetLocationsTest.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/modules/locations/http/emsp/LocationsEmspHttpGetConnectorTest.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/modules/locations/http/emsp/LocationsEmspHttpGetEvseTest.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/modules/locations/http/emsp/LocationsEmspHttpGetLocationTest.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/modules/locations/http/emsp/LocationsEmspHttpPatchConnectorTest.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/modules/locations/http/emsp/LocationsEmspHttpPatchEvseTest.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/modules/locations/http/emsp/LocationsEmspHttpPatchLocationTest.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/modules/locations/http/emsp/LocationsEmspHttpPutConnectorTest.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/modules/locations/http/emsp/LocationsEmspHttpPutEvseTest.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/modules/locations/http/emsp/LocationsEmspHttpPutLocationTest.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/modules/tokens/http/cpo/TokensCpoHttpGetTokenTest.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/modules/tokens/http/cpo/TokensCpoHttpPatchTokenTest.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/modules/tokens/http/cpo/TokensCpoHttpPutTokenTest.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/modules/tokens/http/emsp/TokensEmspHttpGetTokensTest.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/modules/tokens/http/emsp/TokensEmspHttpPostTokenTest.kt

fixes https://github.com/IZIVIA/ocpi-toolkit/issues/151
and makes sure ocpi-toolkit behavior is the same as 0.0.47

fix(mapper): Datetime (instant) parsing was not working if Z was present at the end & added Z at the end for better compat

---

ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/locations/LocationsCpoClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/locations/LocationsEmspInterface.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/locations/services/LocationsEmspService.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/sessions/SessionsCpoClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/sessions/SessionsEmspInterface.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/sessions/services/SessionsEmspService.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/tokens/TokensCpoInterface.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/tokens/TokensEmspClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/tokens/services/TokensCpoService.kt

this should increase compatibility with 3rd party systems, that do not send full objects, while still allowing to send full objects where required.

fix expected return value for data modules

---

buildSrc/src/main/kotlin/Versions.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/common/OcpiInstantDeserializer.kt
ocpi-toolkit-2.2.1/src/test/kotlin/com/izivia/ocpi/toolkit/mappers/MappersTest.kt

adding the Z if timezone info missing would add it when offset was given instead, eg `2025-03-05T10:37:42.13+00:00` would get parsed as `2025-03-05T10:37:42.13+00:00Z`
instead of manipulating the incoming string we simply try various patterns

fix(mapping) #151: timestamps with offset failed to deserialize

---

ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/commands/CommandEmspClient.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/commands/CommandEmspInterface.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/commands/CommandEmspServer.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/commands/domain/CommandResponse.kt
ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/commands/domain/CommandResult.kt

messages field was incorrectly marked as obligatory
client interface now more clearly differentiates between data to be transferred and callback reference
specifically useful when wanting to stop a OCPI session, but using eMSP internal id as callback reference

fix(commands): fix deserialization and client interface
